# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yettings}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["cowboycoded"]
  s.date = %q{2011-03-06}
  s.description = %q{Create settings/contants for your Rails 3 app using yml key/value pairs}
  s.email = %q{john.mcaliley@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/yettings.rb",
    "lib/yettings/railtie.rb",
    "test_app/.gitignore",
    "test_app/.rspec",
    "test_app/Gemfile",
    "test_app/README",
    "test_app/Rakefile",
    "test_app/app/controllers/application_controller.rb",
    "test_app/app/controllers/yettings_controller.rb",
    "test_app/app/helpers/application_helper.rb",
    "test_app/app/views/layouts/application.html.erb",
    "test_app/app/views/yettings/test.html.erb",
    "test_app/config.ru",
    "test_app/config/application.rb",
    "test_app/config/boot.rb",
    "test_app/config/database.yml",
    "test_app/config/environment.rb",
    "test_app/config/environments/development.rb",
    "test_app/config/environments/production.rb",
    "test_app/config/environments/test.rb",
    "test_app/config/initializers/backtrace_silencers.rb",
    "test_app/config/initializers/inflections.rb",
    "test_app/config/initializers/mime_types.rb",
    "test_app/config/initializers/secret_token.rb",
    "test_app/config/initializers/session_store.rb",
    "test_app/config/locales/en.yml",
    "test_app/config/routes.rb",
    "test_app/config/yetting.yml",
    "test_app/config/yettings/hendrix.yml",
    "test_app/config/yettings/jimi.yml",
    "test_app/db/seeds.rb",
    "test_app/lib/tasks/.gitkeep",
    "test_app/public/404.html",
    "test_app/public/422.html",
    "test_app/public/500.html",
    "test_app/public/favicon.ico",
    "test_app/public/images/rails.png",
    "test_app/public/index.html",
    "test_app/public/javascripts/application.js",
    "test_app/public/javascripts/controls.js",
    "test_app/public/javascripts/dragdrop.js",
    "test_app/public/javascripts/effects.js",
    "test_app/public/javascripts/prototype.js",
    "test_app/public/javascripts/rails.js",
    "test_app/public/robots.txt",
    "test_app/public/stylesheets/.gitkeep",
    "test_app/script/rails",
    "test_app/spec/spec_helper.rb",
    "test_app/spec/yettings_spec.rb",
    "test_app/vendor/plugins/.gitkeep"
  ]
  s.homepage = %q{http://github.com/cowboycoded/yettings}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{YAML Settings}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.1.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

