source 'http://rubygems.org'

gem 'rails', '~> 3.2'
gem 'sqlite3', '~> 1.3.5'
gem 'rspec-rails'
gem 'test-unit', '~> 3.0'
gem 'yettings', :path=>"#{File.dirname(__FILE__)}/../"
gem "pry"
gem "awesome_print"
